name: jolly
version: '0.1.0.0'
category: Language
author: John Children
maintainer: john.a.children@gmail.com
copyright: 2017 John Children
license: MIT
github: jchildren/jolly
extra-source-files:
- README.md
dependencies:
  - text
library:
  source-dirs: src
  exposed-modules:
  - Jolly
  other-modules:
  - Jolly.Eval
  - Jolly.Parser
  - Jolly.Pretty
  - Jolly.Syntax
  - Jolly.Syntax.Types
  - Jolly.Types
  - Jolly.Types.Env
  - Jolly.Types.Infer
  - Jolly.Types.System
  dependencies:
  - base >=4.7 && <5
  - megaparsec >=6 && <7
  - containers
  - pretty
  - transformers
  - mtl
executables:
  jolly-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - jolly
    - repline
    - containers
    - mtl
    - megaparsec >=6 && <7
tests:
  jolly-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - jolly
