name: jolly
version: '0.1.0.0'
category: Language
author: John Children
maintainer: john.a.children@gmail.com
copyright: 2017 John Children
license: MIT
github: jchildren/jolly
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Syntax
  - Parser
  - Eval
  - Pretty
  dependencies:
  - base >=4.7 && <5
  - megaparsec
  - containers
  - pretty
executables:
  jolly-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - jolly
    - megaparsec
    - haskeline
tests:
  jolly-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - jolly
